### PR TITLE
Fix module resolution issues in dual CJS/ESM setup

### LINKED ISSUE #257: Issue with importing FocusLock component
## Description:
I'm experiencing an issue when importing the FocusLock component from the react-focus-lock library. Instead of being able to use the component as `<FocusLock>`, I have to use it as `<FocusLock.default>`.

## Steps to reproduce:
1. Create a new Remix project by using `npx create-remix@latest`, with default name, and choose "Just the basics", then the "Express server" deploy target, use TypeScript, run npm install.
2. Install react-focus-lock via `npm i react-focus-lock`.
3. Import the FocusLock component in a React component file with import FocusLock from "react-focus-lock";
4. Try to use the FocusLock component in the JSX code as <FocusLock>.
5. Observe that the component does not work as expected and requires usage as <FocusLock.default>.

## Expected behavior:
I expect to be able to use the FocusLock component as `<FocusLock>` without needing to specify the `.default` property.

## Actual behavior:
The FocusLock component does not work as expected and requires usage as `<FocusLock.default>`.

## Code sample:
```typescript
import React from "react";
import FocusLock from "react-focus-lock";

function MyComponent() {
  return (
    <FocusLock.default>
      <input type="text" />
      <button>Click me</button>
    </FocusLock.default>
  );
}

export default MyComponent;
```

## Environment:
Remix version: 1.19.3
react-focus-lock version: 2.9.5
Browser: Chrome 116.0.5845.96
Operating System: Ubuntu 22.04.3 LTS

## Additional information:
```typescript
import("react-focus-lock").then(pkg => {
  console.log(pkg);
});
```
this will output:
```
[Module: null prototype] {
  AutoFocusInside: [Function: AutoFocusInside] {
    propTypes: {
      children: [Function: bound checkType],
      disabled: [Function],
      className: [Function]
    }
  },
  FocusLockUI: {
    '$$typeof': Symbol(react.forward_ref),
    render: [Function: FocusLockUI],
    propTypes: {
      children: [Function],
      disabled: [Function],
      returnFocus: [Function],
      focusOptions: [Function],
      noFocusGuards: [Function],
      hasPositiveIndices: [Function],
      allowTextSelection: [Function],
      autoFocus: [Function],
      persistentFocus: [Function],
      crossFrame: [Function],
      group: [Function],
      className: [Function],
      whiteList: [Function],
      shards: [Function],
      as: [Function],
      lockProps: [Function],
      onActivation: [Function],
      onDeactivation: [Function],
      sideCar: [Function: bound checkType]
    },
    defaultProps: {
      children: undefined,
      disabled: false,
      returnFocus: false,
      focusOptions: undefined,
      noFocusGuards: false,
      autoFocus: true,
      persistentFocus: false,
      crossFrame: true,
      hasPositiveIndices: undefined,
      allowTextSelection: undefined,
      group: undefined,
      className: undefined,
      whiteList: undefined,
      shards: undefined,
      as: 'div',
      lockProps: {},
      onActivation: undefined,
      onDeactivation: undefined
    }
  },
  FreeFocusInside: [Function: FreeFocusInside] {
    propTypes: { children: [Function: bound checkType], className: [Function] },
    defaultProps: { className: undefined }
  },
  InFocusGuard: [Function: InFocusGuard] {
    propTypes: { children: [Function] },
    defaultProps: { children: null }
  },
  MoveFocusInside: [Function: MoveFocusInside] {
    propTypes: {
      children: [Function: bound checkType],
      disabled: [Function],
      className: [Function]
    },
    defaultProps: { disabled: false, className: undefined }
  },
  __esModule: true,
  default: {
    default: {
      '$$typeof': Symbol(react.forward_ref),
      render: [Function: FocusLockUICombination],
      propTypes: [Object]
    },
    FocusLockUI: [Getter],
    AutoFocusInside: [Getter],
    MoveFocusInside: [Getter],
    useFocusInside: [Getter],
    FreeFocusInside: [Getter],
    InFocusGuard: [Getter]
  },
  useFocusInside: [Function: useFocusInside]
}
```

### PR DESCRIPTION
**Pull request by wojtekmaj**
This PR:
* Marks the package as ESM-first
* Ensures backwards compatibility by keeping all CJS files, keeping `UI` and `sidecar` pseudo-packages for Node.js 10 compatibility, and adding `package.json` in `dist/cjs` to override the above change
* Uses `package.json`'s `exports` to ensure all entry points are still valid - in all modes
* Moves all types to `/src`, so that they sit alongside the modules they belong to, and so that they are copied separately to `/dist/cjs` and `/dist/es2015` directories.

arethetypeswrong CLI shows a clear improvement:

Before:

```
react-focus-lock % attw react-focus-lock-v2.11.3.tgz

react-focus-lock v2.11.3

🤨 CommonJS module simulates a default export with exports.default and exports.__esModule, but does not also set module.exports for compatibility with Node. Node, and some bundlers under certain conditions, do not respect the __esModule marker, so accessing the intended default export will require a .default property access on the default import. https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/CJSOnlyExportsDefault.md


"react-focus-lock"

node10: 🟢 
node16 (from CJS): 🟢 (CJS)
node16 (from ESM): 🤨 CJS default export
bundler: 🤨 CJS default export

***********************************

"react-focus-lock/UI"

node10: 🟢 
node16 (from CJS): 🟢 (CJS)
node16 (from ESM): 🤨 CJS default export
bundler: 🤨 CJS default export

***********************************

"react-focus-lock/sidecar"

node10: 🟢 
node16 (from CJS): 🟢 (CJS)
node16 (from ESM): 🤨 CJS default export
bundler: 🤨 CJS default export

***********************************
```

After:

```
react-focus-lock % attw react-focus-lock-v2.11.3.tgz

react-focus-lock v2.11.3

 No problems found 🌟


"react-focus-lock"

node10: 🟢 
node16 (from CJS): 🟢 (CJS)
node16 (from ESM): 🟢 (ESM)
bundler: 🟢 

***********************************

"react-focus-lock/sidecar"

node10: 🟢 
node16 (from CJS): 🟢 (CJS)
node16 (from ESM): 🟢 (ESM)
bundler: 🟢 

***********************************

"react-focus-lock/UI"

node10: 🟢 
node16 (from CJS): 🟢 (CJS)
node16 (from ESM): 🟢 (ESM)
bundler: 🟢 

***********************************
```

Fixes #257

### CODE REVIEW

File: UI/UI.d.ts
Comment (wojtekmaj) [inline UI/UI.d.ts:1]: This file exists purely for backwards compatibility reasons. Node 16 and up will use `package.json`'s `exports` to resolve `/sidecar` and `/UI` imports.

Comment (wojtekmaj) [inline UI/UI.d.ts:1]: This file is kept purely for backwards compatibility reasons. Node 16 and up will use `package.json`'s `exports` to resolve `/sidecar` and `/UI` imports.

File: UI/package.json
Comment (wojtekmaj) [inline UI/package.json:1]: This file is kept purely for backwards compatibility reasons. Node 16 and up will use `package.json`'s `exports` to resolve `/sidecar` and `/UI` imports.

File: sidecar/package.json
Comment (wojtekmaj) [inline sidecar/package.json:1]: This file is kept purely for backwards compatibility reasons. Node 16 and up will use `package.json`'s `exports` to resolve `/sidecar` and `/UI` imports.

File: src/UI.d.ts
Comment (wojtekmaj) [inline src/UI.d.ts:1]: This file is an exact copy of preexisting `UI.d.ts`, with the exception of import path to `interfaces` type declarations file.

File: src/index.d.ts
Comment (wojtekmaj) [inline src/index.d.ts:1]: As all other declaration files (excl. ones kept for backward compatibility reasons), this file was moved to sit next to the module it belongs to.

File: src/interfaces.d.ts
Comment (wojtekmaj) [inline src/interfaces.d.ts:1]: As all other declaration files (excl. ones kept for backward compatibility reasons), this file was moved to sit next to the module it belongs to.

File: src/interfaces.d.ts [hunk 1]
```diff
@@ -1,7 +1,13 @@
 import * as React from 'react';
-import {Ref} from "react";
+import { Ref } from 'react';
 
-export interface ReactFocusLockProps<ChildrenType = React.ReactNode, LockProps = Record<string, any>> {
+// @FIXME: This was not defined earlier
+type FocusOptions = any;
```
Comment (wojtekmaj) [inline src/interfaces.d.ts:5]: ⚠️ Please note this.

File: src/sidecar.d.ts
Comment (wojtekmaj) [inline src/sidecar.d.ts:1]: This file is an exact copy of preexisting `sidecar.d.ts`.

File: src/interfaces.d.ts (hunk 1 above)
Comment (theKashey) [reply src/interfaces.d.ts:5]: Why no tool consuming this file complained 😭

**Comment by theKashey** [comment]
Give me some time to test integratons.

File: src/interfaces.d.ts (hunk 1 above)
Comment (wojtekmaj) [reply src/interfaces.d.ts:5]: Because no tool was consuming it. TypeScript files were published as-is. They still are, in fact. Only now they sit in a directory that happens to be linted.

**Comment by wojtekmaj** [comment]
One improvement that comes to my mind is that .d.ts files sitting in pseudorepo /sidecar and /UI directories could reexport type definitions from /dist/cjs instead.

**Comment by theKashey** [comment]
I would really like to rewrite focus-lock in TS and don't worry about manual type declarations. So, don't worry about them 😉

**Comment by theKashey** [comment]
Oh, time flies and I am still buried in work. Sorry, should become more free closer to the new year.

**Comment by wojtekmaj** [comment]
Don't worry mate. No one has the right to expect anything from you for $0.

**Comment by wojtekmaj** [comment]
Bad bot!

**Comment by theKashey** [comment]
I am a little hesitant to move forward due to the problem highlighted at https://github.com/gregberge/loadable-components/pull/1003
- single package expected to be a "singleton"
- being imported from ESM and CJS
- ending as two different packages imported and not knowing about each other

This moves change from "just here" to "all consumers".

The "safe" way forward lies in refactoring of `react-clientside-effect` in order to make it "duplication aware", for example via tracking singletons via stable(string) keys.

-----

The question I dont have an answer for - what is required from downstream packages in order to make this one ESM-compatible.
Ie, do I need to _esm_ `react-clientside-effect`, potentially causing the same "duplication" to it, or can keep it as is, making it easier to track references.

@wojtekmaj - I really hope you have some answers for the questions above, well the one question - managing "singleton" in ESM packages.

**Comment by wojtekmaj** [comment]
@theKashey - The approach I took with dual ESM/CJS config presented here was battle tested in React-PDF, React-Calendar, React-Date-Picker and many other packages I maintain.

I do understand your concerns though.

`react-clientside-effect` looks like a fairly simple module ESM should have no issues with. It might be converted to dual CJS/ESM, but doesn't need to be. I confirmed this by running an ESM version of react-focus-lock from this PR in pure Node.js, and checked that `withSideEffect` is still a function and not e.g. `{ default: [Function: withSideEffect] }`.

**Comment by wojtekmaj** [comment]
I rebased the PR off latest master, and edited the first comment, since now the PR is making _everything_ green, not just ESM module resolution!

**Comment by theKashey** [comment]
> and checked that withSideEffect is still a function

More about there is a possibility to reach `withSideEffect` via `require` path and then via `import` path, resulting in two different _worlds_, not one singlenton.
 
Could affect only cases with multiple modals being open using different _ways_ to open them. Not sure how "real" this case is, but it's the only moment that separates this package from others.

**Comment by wojtekmaj** [comment]
> Not sure how "real" this case is

Most bundlers will probably use ESM, because they are capable of resolving ESM. Even if the modules are CJS, they are "wrapped" so that they could all talk to each other seamlessly.
If you don't use any bundler at all, you're *forced* to use ESM, because CJS doesn't work outside of Node.
I may be missing something here, but I don't see how you'd end up with two versions of react-focus-lock. Perhaps in a Node.js-only application, where you could actually use both import in ESM and require in CJS, but that's not a realistic scenario for a front-end package, and also, if you write both ESM and CJS in one Node.js project, you really should reconsider your life choices.

**Comment by theKashey** [comment]
I tend to agree - the problem with `loadable-components` happened at the server side and FocusLock is a purely front-end component, including the "dangerous part" being named as `react-CLIENTSIDE-effect`

**Review by theKashey — APPROVED** [review]

**Comment by theKashey** [comment]
It will take a few days to test it as deeply as I possibly could...

@wojtekmaj+++ and 🙇 for all your effort and impact.
