### PR TITLE
fix: correct focus order for non-autofocusable modals, fixes #340

### LINKED ISSUE #340: Problem with focusing element in modals
Hello. I tried to use the focus lock inside modals and stuck with a problem to focus element. Right now you need press the tab key twice to focus the first element in the modal. **autoFocus** was set to **false** since I don't want to focus any element until press the tab key. Is it possible to focus an element in modals with single tab?

#### Demo:
https://ping-roan.vercel.app/

Just click the "Open modal" button and try to focus any element.

Source code: https://github.com/One041/ping

### PR DESCRIPTION
**Pull request by theKashey**
There is a race conditions non reproducible via unit test where focus event can happen when the old and the new focus points at the body.

The focus restoration logic will try to "reset" itself, but will do it as many times, as many times body can be focused.

- applies only for `autoFocus:false` cases

### CODE REVIEW

File: src/Trap.js [hunk 1]
```diff
@@ -104,15 +104,13 @@ const activateTrap = () => {
...
     // check if lastActiveFocus is still reachable
-    if (focusOnBody() && lastActiveFocus) {
+    if (focusOnBody() && lastActiveFocus && lastActiveFocus !== document.body) {
       if (
         // it was removed
         !document.body.contains(lastActiveFocus)
           // or not focusable (this is expensive operation)!
           || isNotFocusable(lastActiveFocus)
       ) {
-        lastActiveFocus = null;
```
Comment (theKashey) [inline src/Trap.js:114]: causes a "loop"

File: src/Trap.js [hunk 2]
```diff
@@ -104,15 +104,13 @@ const activateTrap = () => {
     const workingNode = observed || (lastPortaledElement && lastPortaledElement.portaledElement);
 
     // check if lastActiveFocus is still reachable
-    if (focusOnBody() && lastActiveFocus) {
+    if (focusOnBody() && lastActiveFocus && lastActiveFocus !== document.body) {
```
Comment (theKashey) [inline src/Trap.js:107]: focus on the body and the last element is body?
Can happen.

Unfortunately `lastActiveFocus` is used to hold the state of the Trap, and it is not just "last active element within trap", it's just "last active element recorded".
For `autoFocus:false` cases it will be `body`
